"""add_metadata_fields_to_downloaded_documents_and_stock_pool

Revision ID: 2d5d913bd156
Revises: 018_add_logs_table
Create Date: 2026-04-09 10:27:31.497138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5d913bd156'
down_revision: Union[str, None] = '018_add_logs_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('analysis_reports', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Agent类型',
               existing_nullable=False)
    op.alter_column('analysis_reports', 'trend',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='趋势判断',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='综合评分',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('announcements', 'ann_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='公告日期',
               existing_nullable=False)
    op.alter_column('announcements', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('announcements', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=True)
    op.alter_column('announcements', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='公告标题',
               existing_nullable=True)
    op.alter_column('announcements', 'type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='公告类型',
               existing_nullable=True)
    op.alter_column('announcements', 'cninfo_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='巨潮公告唯一ID',
               existing_nullable=True)
    op.alter_column('announcements', 'org_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='巨潮机构ID',
               existing_nullable=True)
    op.alter_column('announcements', 'announcement_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='巨潮公告类型编码',
               existing_nullable=True)
    op.alter_column('announcements', 'pdf_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='PDF下载链接',
               existing_nullable=True)
    op.drop_constraint('announcements_cninfo_id_key', 'announcements', type_='unique')
    op.alter_column('concept_limit', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='概念代码',
               existing_nullable=False)
    op.alter_column('concept_limit', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='概念名称',
               existing_nullable=False)
    op.alter_column('concept_limit', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('concept_limit', 'days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='连板天数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'up_stat',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='涨停状态描述',
               existing_nullable=True)
    op.alter_column('concept_limit', 'cons_nums',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成分股数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'up_nums',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='涨停股票数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='概念涨跌幅(%)',
               existing_nullable=True)
    op.alter_column('concept_limit', 'rank',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当日排名',
               existing_nullable=True)
    op.drop_index('idx_concept_limit_unique', table_name='concept_limit')
    op.create_unique_constraint('idx_concept_limit_unique', 'concept_limit', ['concept_code', 'trade_date'])
    op.alter_column('concept_limit_detail', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='概念代码',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='概念名称',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=True)
    op.alter_column('concept_limit_detail', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.drop_index('idx_concept_limit_detail_unique', table_name='concept_limit_detail')
    op.create_unique_constraint('idx_concept_limit_detail_unique', 'concept_limit_detail', ['concept_code', 'ts_code', 'trade_date'])
    op.alter_column('concept_scores', 'concept_ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='THS概念代码',
               existing_nullable=False)
    op.alter_column('concept_scores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='概念名称',
               existing_nullable=True)
    op.alter_column('concept_scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='综合评分 0-100',
               existing_nullable=True)
    op.alter_column('concept_scores', 'momentum_5d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='5日动量',
               existing_nullable=True)
    op.alter_column('concept_scores', 'momentum_1d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='当日涨幅',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='广度（上涨股数/总股数）',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth_rising',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='上涨股票数',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成分股总数',
               existing_nullable=True)
    op.alter_column('concept_scores', 'relative_strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='相对强度（概念涨幅-HS300涨幅）',
               existing_nullable=True)
    op.alter_column('concept_scores', 'stock_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成分股数量',
               existing_nullable=True)
    op.alter_column('concept_scores', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='计算日期',
               existing_nullable=False)
    op.alter_column('concepts', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='概念代码',
               existing_nullable=False)
    op.alter_column('concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='概念名称',
               existing_nullable=False)
    op.alter_column('concepts', 'src',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='来源',
               existing_nullable=True)
    op.alter_column('daily_basic', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('daily_basic', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('daily_basic', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('daily_basic', 'turnover_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'turnover_rate_f',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='自由流通股换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'volume_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='量比',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pe',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='市盈率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pe_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='滚动市盈率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='市净率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'ps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='市销率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'ps_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='滚动市销率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'dv_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='股息率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'dv_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='滚动股息率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'total_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'float_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='流通股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'free_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='自由流通股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'total_mv',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总市值(万元)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'circ_mv',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='流通市值(万元)',
               existing_nullable=True)
    op.alter_column('daily_data', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('daily_data', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='开盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最高价',
               existing_nullable=True)
    op.alter_column('daily_data', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最低价',
               existing_nullable=True)
    op.alter_column('daily_data', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='前收盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌额',
               existing_nullable=True)
    op.alter_column('daily_data', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('daily_data', 'vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交量(手)',
               existing_nullable=True)
    op.alter_column('daily_data', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交额(千元)',
               existing_nullable=True)
    op.alter_column('daily_data', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否停牌')
    op.add_column('downloaded_documents', sa.Column('source_type', sa.String(length=30), server_default='cninfo_document', nullable=False))
    op.add_column('downloaded_documents', sa.Column('source_name', sa.String(length=50), server_default='巨潮资讯PDF', nullable=False))
    op.add_column('downloaded_documents', sa.Column('confidence_tier', sa.String(length=10), server_default='Tier 1', nullable=False))
    op.add_column('downloaded_documents', sa.Column('parser_version', sa.String(length=10), server_default='v1.0', nullable=False))
    op.add_column('downloaded_documents', sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('downloaded_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('downloaded_documents', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('idx_doc_cninfo_id_unique', 'downloaded_documents', ['cninfo_id'])
    op.alter_column('index_daily', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='指数代码',
               existing_nullable=False)
    op.alter_column('index_daily', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('index_daily', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='开盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最高价',
               existing_nullable=True)
    op.alter_column('index_daily', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最低价',
               existing_nullable=True)
    op.alter_column('index_daily', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='前收盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌额',
               existing_nullable=True)
    op.alter_column('index_daily', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('index_daily', 'vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交量',
               existing_nullable=True)
    op.alter_column('index_daily', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成交额',
               existing_nullable=True)
    op.alter_column('monitor_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='规则类型',
               existing_nullable=False)
    op.alter_column('monitor_rules', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='阈值',
               existing_nullable=False)
    op.alter_column('monitor_rules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('monitor_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_documents', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='来源',
               existing_nullable=True)
    op.alter_column('research_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_report_meta', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('research_report_meta', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码（可能为空）',
               existing_nullable=True)
    op.alter_column('research_report_meta', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='文件名',
               existing_nullable=False)
    op.alter_column('research_report_meta', 'author',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='分析师',
               existing_nullable=True)
    op.alter_column('research_report_meta', 'inst_csname',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='机构名称',
               existing_nullable=True)
    op.drop_index('idx_rmeta_unique', table_name='research_report_meta')
    op.create_unique_constraint('idx_rmeta_unique', 'research_report_meta', ['trade_date', 'file_name'])
    op.alter_column('stock_concepts', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_concepts', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='概念代码',
               existing_nullable=False)
    op.drop_index('idx_stock_concepts_unique', table_name='stock_concepts')
    op.create_unique_constraint('idx_stock_concepts_unique', 'stock_concepts', ['ts_code', 'concept_code'])
    op.add_column('stock_pool', sa.Column('source_type', sa.String(length=30), server_default='ths_concept', nullable=False))
    op.add_column('stock_pool', sa.Column('source_name', sa.String(length=50), server_default='THS同花顺概念', nullable=False))
    op.add_column('stock_pool', sa.Column('confidence_tier', sa.String(length=10), server_default='Tier 0', nullable=False))
    op.add_column('stock_pool', sa.Column('parser_version', sa.String(length=10), server_default='v1.0', nullable=False))
    op.add_column('stock_pool', sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('stock_pool', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_pool', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='所属强势板块代码（TI格式）',
               existing_nullable=True)
    op.alter_column('stock_pool', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='所属强势板块名称',
               existing_nullable=True)
    op.alter_column('stock_pool', 'in_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='纳入日期',
               existing_nullable=False)
    op.alter_column('stock_pool', 'out_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='剔除日期（NULL=仍在池中）',
               existing_nullable=True)
    op.alter_column('stock_pool', 'pct_chg_5d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='近5日累计涨幅',
               existing_nullable=True)
    op.alter_column('stock_pool', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='综合评分',
               existing_nullable=True)
    op.drop_index('idx_pool_out', table_name='stock_pool', postgresql_where='(out_date IS NULL)')
    op.alter_column('stock_scores', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_scores', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=True)
    op.alter_column('stock_scores', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总分 0-100',
               existing_nullable=True)
    op.alter_column('stock_scores', 'momentum_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='动量分 0-25',
               existing_nullable=True)
    op.alter_column('stock_scores', 'trend_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='趋势分 0-30',
               existing_nullable=True)
    op.alter_column('stock_scores', 'capital_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='资金面分 0-25',
               existing_nullable=True)
    op.alter_column('stock_scores', 'concept_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='概念溢价 0-15',
               existing_nullable=True)
    op.alter_column('stock_scores', 'valuation_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='估值加分 0-5',
               existing_nullable=True)
    op.alter_column('stock_scores', 'momentum_5d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='近5日累计涨幅',
               existing_nullable=True)
    op.alter_column('stock_scores', 'turnover_rate_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='换手率',
               existing_nullable=True)
    op.alter_column('stock_scores', 'vol_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='量比',
               existing_nullable=True)
    op.alter_column('stock_scores', 'ma_state',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='均线状态',
               existing_nullable=True)
    op.alter_column('stock_scores', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='计算日期',
               existing_nullable=False)
    op.alter_column('stocks', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stocks', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='股票简码',
               existing_nullable=False)
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=False)
    op.alter_column('stocks', 'area',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='所在地区',
               existing_nullable=True)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='所属行业',
               existing_nullable=True)
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='市场类型',
               existing_nullable=True)
    op.alter_column('stocks', 'list_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='上市日期',
               existing_nullable=True)
    op.alter_column('stocks', 'is_hs',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='是否沪深港通',
               existing_nullable=True)
    op.alter_column('ths_concept_members', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='THS概念代码',
               existing_nullable=False)
    op.alter_column('ths_concept_members', 'con_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='成分股代码，如 000016.SZ',
               existing_nullable=False)
    op.alter_column('ths_concept_members', 'con_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='成分股名称',
               existing_nullable=True)
    op.alter_column('ths_concept_members', 'in_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='纳入日期',
               existing_nullable=True)
    op.drop_index('idx_ths_member_unique', table_name='ths_concept_members')
    op.create_unique_constraint('idx_ths_member_unique', 'ths_concept_members', ['ts_code', 'con_code'])
    op.alter_column('ths_concepts', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='THS概念代码，如 885800.TI',
               existing_nullable=False)
    op.alter_column('ths_concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='概念名称',
               existing_nullable=False)
    op.alter_column('ths_concepts', 'count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成分股数量',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='所属交易所：A=全部，N=概念，E=行业',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'list_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='纳入日期',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='类型：N=概念，E=行业',
               existing_nullable=True)
    op.alter_column('watchlist', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment=None,
               existing_comment='添加时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('watchlist', 'note',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.drop_index('idx_watchlist_ts_code', table_name='watchlist')
    op.create_unique_constraint('idx_watchlist_ts_code', 'watchlist', ['ts_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_watchlist_ts_code', 'watchlist', type_='unique')
    op.create_index('idx_watchlist_ts_code', 'watchlist', ['ts_code'], unique=True)
    op.alter_column('watchlist', 'note',
               existing_type=sa.VARCHAR(length=200),
               comment='备注',
               existing_nullable=True)
    op.alter_column('watchlist', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment='添加时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('ths_concepts', 'type',
               existing_type=sa.VARCHAR(length=10),
               comment='类型：N=概念，E=行业',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'list_date',
               existing_type=sa.DATE(),
               comment='纳入日期',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               comment='所属交易所：A=全部，N=概念，E=行业',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'count',
               existing_type=sa.INTEGER(),
               comment='成分股数量',
               existing_nullable=True)
    op.alter_column('ths_concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='概念名称',
               existing_nullable=False)
    op.alter_column('ths_concepts', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='THS概念代码，如 885800.TI',
               existing_nullable=False)
    op.drop_constraint('idx_ths_member_unique', 'ths_concept_members', type_='unique')
    op.create_index('idx_ths_member_unique', 'ths_concept_members', ['ts_code', 'con_code'], unique=True)
    op.alter_column('ths_concept_members', 'in_date',
               existing_type=sa.DATE(),
               comment='纳入日期',
               existing_nullable=True)
    op.alter_column('ths_concept_members', 'con_name',
               existing_type=sa.VARCHAR(length=50),
               comment='成分股名称',
               existing_nullable=True)
    op.alter_column('ths_concept_members', 'con_code',
               existing_type=sa.VARCHAR(length=20),
               comment='成分股代码，如 000016.SZ',
               existing_nullable=False)
    op.alter_column('ths_concept_members', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='THS概念代码',
               existing_nullable=False)
    op.alter_column('stocks', 'is_hs',
               existing_type=sa.VARCHAR(length=1),
               comment='是否沪深港通',
               existing_nullable=True)
    op.alter_column('stocks', 'list_date',
               existing_type=sa.DATE(),
               comment='上市日期',
               existing_nullable=True)
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment='市场类型',
               existing_nullable=True)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment='所属行业',
               existing_nullable=True)
    op.alter_column('stocks', 'area',
               existing_type=sa.VARCHAR(length=50),
               comment='所在地区',
               existing_nullable=True)
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=False)
    op.alter_column('stocks', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='股票简码',
               existing_nullable=False)
    op.alter_column('stocks', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_scores', 'trade_date',
               existing_type=sa.DATE(),
               comment='计算日期',
               existing_nullable=False)
    op.alter_column('stock_scores', 'ma_state',
               existing_type=sa.VARCHAR(length=20),
               comment='均线状态',
               existing_nullable=True)
    op.alter_column('stock_scores', 'vol_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='量比',
               existing_nullable=True)
    op.alter_column('stock_scores', 'turnover_rate_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='换手率',
               existing_nullable=True)
    op.alter_column('stock_scores', 'momentum_5d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='近5日累计涨幅',
               existing_nullable=True)
    op.alter_column('stock_scores', 'valuation_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='估值加分 0-5',
               existing_nullable=True)
    op.alter_column('stock_scores', 'concept_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='概念溢价 0-15',
               existing_nullable=True)
    op.alter_column('stock_scores', 'capital_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='资金面分 0-25',
               existing_nullable=True)
    op.alter_column('stock_scores', 'trend_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='趋势分 0-30',
               existing_nullable=True)
    op.alter_column('stock_scores', 'momentum_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='动量分 0-25',
               existing_nullable=True)
    op.alter_column('stock_scores', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总分 0-100',
               existing_nullable=True)
    op.alter_column('stock_scores', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=True)
    op.alter_column('stock_scores', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.create_index('idx_pool_out', 'stock_pool', ['out_date'], unique=True, postgresql_where='(out_date IS NULL)')
    op.alter_column('stock_pool', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='综合评分',
               existing_nullable=True)
    op.alter_column('stock_pool', 'pct_chg_5d',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='近5日累计涨幅',
               existing_nullable=True)
    op.alter_column('stock_pool', 'out_date',
               existing_type=sa.DATE(),
               comment='剔除日期（NULL=仍在池中）',
               existing_nullable=True)
    op.alter_column('stock_pool', 'in_date',
               existing_type=sa.DATE(),
               comment='纳入日期',
               existing_nullable=False)
    op.alter_column('stock_pool', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment='所属强势板块名称',
               existing_nullable=True)
    op.alter_column('stock_pool', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment='所属强势板块代码（TI格式）',
               existing_nullable=True)
    op.alter_column('stock_pool', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.drop_column('stock_pool', 'extracted_at')
    op.drop_column('stock_pool', 'parser_version')
    op.drop_column('stock_pool', 'confidence_tier')
    op.drop_column('stock_pool', 'source_name')
    op.drop_column('stock_pool', 'source_type')
    op.drop_constraint('idx_stock_concepts_unique', 'stock_concepts', type_='unique')
    op.create_index('idx_stock_concepts_unique', 'stock_concepts', ['ts_code', 'concept_code'], unique=True)
    op.alter_column('stock_concepts', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment='概念代码',
               existing_nullable=False)
    op.alter_column('stock_concepts', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.drop_constraint('idx_rmeta_unique', 'research_report_meta', type_='unique')
    op.create_index('idx_rmeta_unique', 'research_report_meta', ['trade_date', 'file_name'], unique=True)
    op.alter_column('research_report_meta', 'inst_csname',
               existing_type=sa.VARCHAR(length=200),
               comment='机构名称',
               existing_nullable=True)
    op.alter_column('research_report_meta', 'author',
               existing_type=sa.VARCHAR(length=200),
               comment='分析师',
               existing_nullable=True)
    op.alter_column('research_report_meta', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment='文件名',
               existing_nullable=False)
    op.alter_column('research_report_meta', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码（可能为空）',
               existing_nullable=True)
    op.alter_column('research_report_meta', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('research_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('research_documents', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='来源',
               existing_nullable=True)
    op.alter_column('monitor_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monitor_rules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('monitor_rules', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='阈值',
               existing_nullable=False)
    op.alter_column('monitor_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               comment='规则类型',
               existing_nullable=False)
    op.alter_column('index_daily', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交额',
               existing_nullable=True)
    op.alter_column('index_daily', 'vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交量',
               existing_nullable=True)
    op.alter_column('index_daily', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('index_daily', 'change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌额',
               existing_nullable=True)
    op.alter_column('index_daily', 'pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='前收盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最低价',
               existing_nullable=True)
    op.alter_column('index_daily', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最高价',
               existing_nullable=True)
    op.alter_column('index_daily', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='开盘价',
               existing_nullable=True)
    op.alter_column('index_daily', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('index_daily', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='指数代码',
               existing_nullable=False)
    op.drop_constraint('idx_doc_cninfo_id_unique', 'downloaded_documents', type_='unique')
    op.alter_column('downloaded_documents', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('downloaded_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('downloaded_documents', 'extracted_at')
    op.drop_column('downloaded_documents', 'parser_version')
    op.drop_column('downloaded_documents', 'confidence_tier')
    op.drop_column('downloaded_documents', 'source_name')
    op.drop_column('downloaded_documents', 'source_type')
    op.alter_column('daily_data', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否停牌')
    op.alter_column('daily_data', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交额(千元)',
               existing_nullable=True)
    op.alter_column('daily_data', 'vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成交量(手)',
               existing_nullable=True)
    op.alter_column('daily_data', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('daily_data', 'change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='涨跌额',
               existing_nullable=True)
    op.alter_column('daily_data', 'pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='前收盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最低价',
               existing_nullable=True)
    op.alter_column('daily_data', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最高价',
               existing_nullable=True)
    op.alter_column('daily_data', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='开盘价',
               existing_nullable=True)
    op.alter_column('daily_data', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('daily_basic', 'circ_mv',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='流通市值(万元)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'total_mv',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总市值(万元)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'free_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='自由流通股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'float_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='流通股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'total_share',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总股本(万股)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'dv_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='滚动股息率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'dv_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='股息率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'ps_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='滚动市销率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'ps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='市销率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='市净率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pe_ttm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='滚动市盈率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'pe',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='市盈率',
               existing_nullable=True)
    op.alter_column('daily_basic', 'volume_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='量比',
               existing_nullable=True)
    op.alter_column('daily_basic', 'turnover_rate_f',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='自由流通股换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'turnover_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_basic', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('daily_basic', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('daily_basic', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('concepts', 'src',
               existing_type=sa.VARCHAR(length=20),
               comment='来源',
               existing_nullable=True)
    op.alter_column('concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='概念名称',
               existing_nullable=False)
    op.alter_column('concepts', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='概念代码',
               existing_nullable=False)
    op.alter_column('concept_scores', 'trade_date',
               existing_type=sa.DATE(),
               comment='计算日期',
               existing_nullable=False)
    op.alter_column('concept_scores', 'stock_count',
               existing_type=sa.INTEGER(),
               comment='成分股数量',
               existing_nullable=True)
    op.alter_column('concept_scores', 'relative_strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='相对强度（概念涨幅-HS300涨幅）',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth_total',
               existing_type=sa.INTEGER(),
               comment='成分股总数',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth_rising',
               existing_type=sa.INTEGER(),
               comment='上涨股票数',
               existing_nullable=True)
    op.alter_column('concept_scores', 'breadth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='广度（上涨股数/总股数）',
               existing_nullable=True)
    op.alter_column('concept_scores', 'momentum_1d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='当日涨幅',
               existing_nullable=True)
    op.alter_column('concept_scores', 'momentum_5d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='5日动量',
               existing_nullable=True)
    op.alter_column('concept_scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='综合评分 0-100',
               existing_nullable=True)
    op.alter_column('concept_scores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='概念名称',
               existing_nullable=True)
    op.alter_column('concept_scores', 'concept_ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='THS概念代码',
               existing_nullable=False)
    op.drop_constraint('idx_concept_limit_detail_unique', 'concept_limit_detail', type_='unique')
    op.create_index('idx_concept_limit_detail_unique', 'concept_limit_detail', ['concept_code', 'ts_code', 'trade_date'], unique=True)
    op.alter_column('concept_limit_detail', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=True)
    op.alter_column('concept_limit_detail', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment='概念名称',
               existing_nullable=False)
    op.alter_column('concept_limit_detail', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment='概念代码',
               existing_nullable=False)
    op.drop_constraint('idx_concept_limit_unique', 'concept_limit', type_='unique')
    op.create_index('idx_concept_limit_unique', 'concept_limit', ['concept_code', 'trade_date'], unique=True)
    op.alter_column('concept_limit', 'rank',
               existing_type=sa.INTEGER(),
               comment='当日排名',
               existing_nullable=True)
    op.alter_column('concept_limit', 'pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='概念涨跌幅(%)',
               existing_nullable=True)
    op.alter_column('concept_limit', 'up_nums',
               existing_type=sa.INTEGER(),
               comment='涨停股票数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'cons_nums',
               existing_type=sa.INTEGER(),
               comment='成分股数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'up_stat',
               existing_type=sa.VARCHAR(length=50),
               comment='涨停状态描述',
               existing_nullable=True)
    op.alter_column('concept_limit', 'days',
               existing_type=sa.INTEGER(),
               comment='连板天数',
               existing_nullable=True)
    op.alter_column('concept_limit', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('concept_limit', 'concept_name',
               existing_type=sa.VARCHAR(length=100),
               comment='概念名称',
               existing_nullable=False)
    op.alter_column('concept_limit', 'concept_code',
               existing_type=sa.VARCHAR(length=20),
               comment='概念代码',
               existing_nullable=False)
    op.create_unique_constraint('announcements_cninfo_id_key', 'announcements', ['cninfo_id'])
    op.alter_column('announcements', 'pdf_url',
               existing_type=sa.TEXT(),
               comment='PDF下载链接',
               existing_nullable=True)
    op.alter_column('announcements', 'announcement_type',
               existing_type=sa.TEXT(),
               comment='巨潮公告类型编码',
               existing_nullable=True)
    op.alter_column('announcements', 'org_id',
               existing_type=sa.VARCHAR(length=50),
               comment='巨潮机构ID',
               existing_nullable=True)
    op.alter_column('announcements', 'cninfo_id',
               existing_type=sa.VARCHAR(length=100),
               comment='巨潮公告唯一ID',
               existing_nullable=True)
    op.alter_column('announcements', 'type',
               existing_type=sa.TEXT(),
               comment='公告类型',
               existing_nullable=True)
    op.alter_column('announcements', 'title',
               existing_type=sa.TEXT(),
               comment='公告标题',
               existing_nullable=True)
    op.alter_column('announcements', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='股票名称',
               existing_nullable=True)
    op.alter_column('announcements', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('announcements', 'ann_date',
               existing_type=sa.DATE(),
               comment='公告日期',
               existing_nullable=False)
    op.alter_column('analysis_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analysis_reports', 'score',
               existing_type=sa.INTEGER(),
               comment='综合评分',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'trend',
               existing_type=sa.VARCHAR(length=20),
               comment='趋势判断',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Agent类型',
               existing_nullable=False)
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alerts', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
